//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Band:IMG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Band()
        {
            this.Albums = new HashSet<Albums>();
        }
    
        public int bBandID { get; set; }
        public string bBandName { get; set; }
        public Nullable<int> bRecordID { get; set; }
        public Nullable<int> bBTypeID { get; set; }
        public string bStatus { get; set; }
        public string bBandProfile { get; set; }
        public byte[] bPicturebands { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Albums> Albums { get; set; }
        public virtual BandType BandType { get; set; }
        public virtual Record Record { get; set; }
    }
}
